Repository FluidInference/FluidAudio, pull requests merged in 2025-08, with the labels that each got.

#58 fix: vocabulary loading ignores custom model directory
  Sources/FluidAudio/ASR/AsrManager.swift
  Sources/FluidAudio/ASR/AsrModels.swift
Labels: bug

#72 fix: URLSession.shared do not respect env https_proxy
  README.md
  Sources/FluidAudio/DownloadUtils.swift
  Sources/FluidAudioCLI/Commands/AsrBenchmark.swift
  Sources/FluidAudioCLI/DatasetParsers/DatasetDownloader.swift
Labels: enhancement

#85 Fix RTFx calculation in benchmarks
  Sources/FluidAudioCLI/Commands/ASR/AsrBenchmark.swift
  Sources/FluidAudioCLI/Commands/ASR/AsrBenchmarkTypes.swift
  Sources/FluidAudioCLI/Commands/ASR/FleursBenchmark.swift
  Sources/FluidAudioCLI/Commands/ASR/TranscribeCommand.swift
  Sources/FluidAudioCLI/Commands/DiarizationBenchmark.swift
  Sources/FluidAudioCLI/Commands/FleursHighWerAnalysis.swift
Labels: bug, ASR

#80 Add Silero VAD v2 model with simplified audio processing
  .github/workflows/vad-benchmark.yml
  CLAUDE.md
  README.md
  Sources/FluidAudio/VAD/VadAudioProcessor.swift
  Sources/FluidAudio/VAD/VadManager.swift
  Sources/FluidAudio/VAD/VadModelProcessor.swift
  Sources/FluidAudio/VAD/VadTypes.swift
  Sources/FluidAudioCLI/Commands/VadBenchmark.swift
  Sources/FluidAudioCLI/README.md
  Tests/FluidAudioTests/VadTests.swift
Labels: enhancement
